//external
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

//internal
import { GlobalStyles } from "@/styles/globalStyles";
import { Providers as ThemeProvider } from "@/styles/themeProvider";
import { ReactQueryProvider } from "@/logic/reactQuery/queryClientProvider";
import { ReduxProvider } from "@/logic/redux/reduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <ReactQueryProvider>
          <ReduxProvider>
            <ThemeProvider>
              <GlobalStyles />
              {children}
            </ThemeProvider>
          </ReduxProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
